### ISSUE TITLE
Not really an issue, but more of a question.

### ISSUE THREAD

**Issue by SwirlyStone5877** [wiiu-env/NotificationModule#1]
What does this even do? Does it allow homebrew to send notifs or what?

**Comment by c08oprkiua** [comment]
Yeah it allows homebrew to send Aroma notifications. These aren't the system notifications you'd see in the Notifications Applet, rather they're popup notifications that appear in the top left corner of the screen

**Comment by SwirlyStone5877** [comment]
Nice.
